---
- name: Create a new EC2 key
  amazon.aws.ec2_key:
    name: "ansible_ec2_key"
    key_type: "rsa"
    tags: "{{ default_tags }}"
    state: present
  register: ec2_key_result

- name: Save Private Key
  copy:
    content: "{{ ec2_key_result.key.private_key }}"
    dest: "./private_key.pem"
    mode: 0600
  when: ec2_key_result.changed
