---
- hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yaml
  tasks:
    - include_tasks: keys.yaml
    - include_tasks: vpc.yaml
    - include_tasks: ec2.yaml

- hosts: ec2hosts
  gather_facts: false
  remote_user: ubuntu
  become: true
  vars:
    ansible_ssh_private_key_file: "./private_key.pem"
  tasks:
    - include_tasks: nginx.yaml
