---
- hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yaml
  tasks:
    - name: Terminate EC2 instance
      amazon.aws.ec2_instance:
        region: "{{ aws_region }}"
        filters:
          instance-state-name: running
          "tag:Name": "ec2_instance"
          "tag:Env": "{{ default_tags.Env }}"
          "tag:Owner": "{{ default_tags.Owner }}"
        state: absent

    - name: Delete Security Group
      amazon.aws.ec2_group:
        name: "instance_access"
        region: "{{ aws_region }}"
        tags: "{{ default_tags }}"
        state: absent

    - name: Get VPC details
      amazon.aws.ec2_vpc_net_info:
        region: "{{ aws_region }}"
        filters:
          "tag:Name": "ec2_vpc"
          "tag:Env": "{{ default_tags.Env }}"
          "tag:Owner": "{{ default_tags.Owner }}"
      register: vpc_result

    - name: Delete VPC Public Subnet Route Table
      amazon.aws.ec2_vpc_route_table:
        region: "{{ aws_region }}"
        vpc_id: "{{ vpc_result.vpcs[0].vpc_id }}"
        tags: "{{ default_tags }}"
        state: absent

    - name: Delete VPC Internet Gateway
      amazon.aws.ec2_vpc_igw:
        region: "{{ aws_region }}"
        vpc_id: "{{ vpc_result.vpcs[0].vpc_id }}"
        tags: "{{ default_tags }}"
        state: absent

    - name: Delete Public Subnet
      amazon.aws.ec2_vpc_subnet:
        region: "{{ aws_region }}"
        vpc_id: "{{ vpc_result.vpcs[0].vpc_id }}"
        cidr: 10.20.1.0/24
        tags: "{{ default_tags }}"
        state: absent

    - name: Delete VPC
      amazon.aws.ec2_vpc_net:
        name: ec2_vpc
        region: "{{ aws_region }}"
        cidr_block: 10.20.0.0/16
        tags: "{{ default_tags }}"
        state: absent

    - name: Delete EC2 key
      amazon.aws.ec2_key:
        name: "ansible_ec2_key"
        region: "{{ aws_region }}"
        tags: "{{ default_tags }}"
        state: absent
  
    - name: Delete Private Key
      file:
        path: "./private_key.pem"
        state: absent
