---
- name: Create VPC
  amazon.aws.ec2_vpc_net:
    name: ec2_vpc
    cidr_block: 10.20.0.0/16
    tags: "{{ default_tags }}"
    state: present
  register: vpc_result

- name: Create Public Subnet
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc_result.vpc.id }}"
    cidr: 10.20.1.0/24
    tags: "{{ default_tags }}"
    state: present
  register: subnet_result

- name: Create VPC Internet Gateway
  amazon.aws.ec2_vpc_igw:
    vpc_id: "{{ vpc_result.vpc.id }}"
    tags: "{{ default_tags }}"
    state: present
  register: igw_result

- name: Create VPC Public Subnet Route Table
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ vpc_result.vpc.id }}"
    subnets:
      - "{{ subnet_result.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw_result.gateway_id }}"
    tags: "{{ default_tags }}"
    state: present

- name: Create EC2 Security Group
  amazon.aws.ec2_group:
    name: "instance_access"
    description: "ec2_group"
    vpc_id: "{{ vpc_result.vpc.id }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "0.0.0.0/0"
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: "0.0.0.0/0"
    rules_egress:
      - proto: -1
        from_port: 0
        to_port: 0
        cidr_ip: "0.0.0.0/0"
    tags: "{{ default_tags }}"
    state: present
  register: sg_result
